### ISSUE TITLE
CPAN testers fails to run v0.400001 test harness unless Test::Fatal is installed

### ISSUE THREAD

**Issue by chansen** [p5pclub/http-xsheaders#3]
The test files `t/_header.t` and `t/validate_invocant.t` are incorrect, they should either use a `plan` and a `SKIP {}` block if `Test::Fatal` isn't available or remove the plan and use `done_testing()`.

[v0.400001 Fail reports](http://www.cpantesters.org/distro/H/HTTP-XSHeaders.html#HTTP-XSHeaders-0.400001).

**Comment by xsawyerx** [comment]
Will fix and release a new version ASAP. Thanks! :)

**Comment by xsawyerx** [comment]
Just released a new version removing `Test::Fatal` entirely.

**Comment by chansen** [comment]
Excellent :o)!
