### ISSUE TITLE
-Wno-gnu-statement-expression not available in some (older?) gcc versions [rt.cpan.org #108199]

### ISSUE THREAD

**Issue by xsawyerx** [p5pclub/http-xsheaders#5]
Migrated from [rt.cpan.org#108199](https://rt.cpan.org/Ticket/Display.html?id=108199) (status was 'new')

Requestors:
* SREZIC@cpan.org

From srezic@cpan.org on 2015-10-30 14:36:03:
```
See http://matrix.cpantesters.org/?dist=HTTP-XSHeaders%200.400002 for an overview of successful (green coloring) and unsuccessful builds (yellow coloring). In the case of freebsd 9.2 it was sufficient to remove -Wno-gnu-statement-expression from CCFLAGS to get a successful build (and test).
```

**Comment by gonzus** [comment]
@srezic@cpan.org I have fixed this and will soon publish a new version in CPAN. Thanks for your report!
